/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as OutfitsRouteImport } from './routes/outfits'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FfRouteImport } from './routes/ff'
import { Route as ConverterRouteImport } from './routes/converter'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const OutfitsRoute = OutfitsRouteImport.update({
  id: '/outfits',
  path: '/outfits',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FfRoute = FfRouteImport.update({
  id: '/ff',
  path: '/ff',
  getParentRoute: () => rootRouteImport,
} as any)
const ConverterRoute = ConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/converter': typeof ConverterRoute
  '/ff': typeof FfRoute
  '/gallery': typeof GalleryRoute
  '/outfits': typeof OutfitsRoute
  '/tools': typeof ToolsRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/converter': typeof ConverterRoute
  '/ff': typeof FfRoute
  '/gallery': typeof GalleryRoute
  '/outfits': typeof OutfitsRoute
  '/tools': typeof ToolsRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/converter': typeof ConverterRoute
  '/ff': typeof FfRoute
  '/gallery': typeof GalleryRoute
  '/outfits': typeof OutfitsRoute
  '/tools': typeof ToolsRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/converter'
    | '/ff'
    | '/gallery'
    | '/outfits'
    | '/tools'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/converter'
    | '/ff'
    | '/gallery'
    | '/outfits'
    | '/tools'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/converter'
    | '/ff'
    | '/gallery'
    | '/outfits'
    | '/tools'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConverterRoute: typeof ConverterRoute
  FfRoute: typeof FfRoute
  GalleryRoute: typeof GalleryRoute
  OutfitsRoute: typeof OutfitsRoute
  ToolsRoute: typeof ToolsRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outfits': {
      id: '/outfits'
      path: '/outfits'
      fullPath: '/outfits'
      preLoaderRoute: typeof OutfitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ff': {
      id: '/ff'
      path: '/ff'
      fullPath: '/ff'
      preLoaderRoute: typeof FfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converter': {
      id: '/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConverterRoute: ConverterRoute,
  FfRoute: FfRoute,
  GalleryRoute: GalleryRoute,
  OutfitsRoute: OutfitsRoute,
  ToolsRoute: ToolsRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
